# Load packages
library(shiny)
library(shinyjs)
library(bs4Dash)
library(thematic)
library(waiter)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringi)
library(stringr)
library(leaflet)
library(leaflet.minicharts)
library(data.table)
library(summaryBox) #remotes::install_github("deepanshu88/summaryBox")
library(plotly)
library(ggplot2)
library(shinyWidgets)
library(shinyThings) #devtools::install_github("gadenbuie/shinyThings")
library(shinyalert)

